version: "3.9"
services:
    db:
        image: postgres:alpine
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: password
    web:
        build: .
        command: sh -c "bundle exec rails s -p 3000 -b 0.0.0.0"
        volumes:
            - .:/afm-api
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment:
            DATABASE_URL: postgres://postgres:password@db
            RAILS_ENV: "development"